site_name: Yona Language
#strict: true
use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - admonition
  - attr_list

plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - minify:
      minify_html: true
  - awesome-pages

repo_name: yona-lang/yona
repo_url: https://github.com/yona-lang/yona
site_url: http://yona-lang.org/

extra:
  analytics:
    provider: google
    property: G-2HXE35KSZ3
  consent:
    title: Cookie consent
    description: > 
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better.
  disqus: yona-lang
